### ISSUE TITLE
[Request] Little Logistic and Aquaculture fishes

### ISSUE THREAD

**Issue by lays24mc** [MuradAkh/LittleLogistics#152]
Hi,

first of all I want to say that the mod is really very cool. I am currently using the Auto-Fisher. However, I noticed that it only collects vanilla loot. Is there any way that the mod can also collect fish from Aquaculture 2? :)

**Comment by MuradAkh** [comment]
This is actually configureable and used in some modpacks like Enigmatica 6. The issue is that some mods write directly to the fishing loot able instead of the fish loot table that the barges use for non-treasure loot.  

You can find the server config file inside your save game and change the loot table, please note this will also mean that fishing barges will now pick up junk. 

Here's the config file user by enigmatica 6:
https://github.com/EnigmaticaModpacks/Enigmatica6/blob/master/defaultconfigs/littlelogistics-server.toml

**Comment by lays24mc** [comment]
Thank you for pointing this out. I had no longer thought that there is still a serverconfig xD
