### ISSUE TITLE
Train falls apart in between logins

### ISSUE THREAD

**Issue by ncottrill** [MuradAkh/LittleLogistics#192]
Hi,

I love this mod! On our server, the tug continues working between my logins to the active area (we have an auto-fisher with a chunkloader attached  tug-fisher-fisher-fisher-chunkloader). However, when I log back in after a time, the train has fallen apart (lost the chains?). It does this in various places, so it isn't placement or a particular area. I just logged in and found the train deep in the subway (it is the only entity there), in pieces. The train also has a chunk loader attached (coal locomotive-chest-chest-chest-chunk loader). 

Any suggestions about how to keep the train "together" on the server between logins to the area?

**Comment by wertercatt** [comment]
This also happens to me when the server shuts down.

**Comment by MuradAkh** [comment]
How long is the train? It's possible that part of it is outside of the chunkloader's range.  We do have a bunch of trains on our test server and never encountered this issue

**Comment by MuradAkh** [comment]
This generally shouldn't be the issue, I don't think logins could be impacting it since it's chunkloaded. I wonder if the chunkloader isn't working for you for some reason? Like the server is overstressed or something and it can't load more chunks, I recommend checking the logs to see if you have anything like that.

We have a bunch of trains on our test server and I've never encountered this issue.

One common cause of train disconnections are mobs getting between cars, although I guess it's unlikely in your subway. It could also happen as a result of weird junctions etc (the + junction rail would probably be the most likely culprit)  or perhaps rails from other mods.

Lastly, make sure you have the latest version of the mod. 

If you would like, you can include a world download and a mod list and I can try investigating the issue for your specific case, or a video of the track would help too

**Comment by MuradAkh** [comment]
> This also happens to me when the server shuts down.

That's interesting, you mean on any regular server restarts? Have you by any chance changed the speed of the trains in the config? Do you have any server-side optimisation mods that could mess with loading? We do have some new code in version 1.2.4 to try to prevent this, although if you already had to a loader that shouldn't have happened before either

**Comment by ncottrill** [comment]
Our world is 3+Gb. I could send you a dropbox link to it, privately, if you're amenable to the "not on GitHub" public posting of it.

**Comment by MuradAkh** [comment]
Ugh that's quite large, perhaps a video of going though the track would be best, and maybe screenshots of broken trains and the area. But yeah since the world is quite large it's possible it's due to chunkloading failures

**Comment by ncottrill** [comment]
Ok, I'll see what we can do re: videos. We have 22 players, so it is likely the size. We have it embedded in Minecolonies and each of those colonies can have 50 to 250 citizens (entities). It might very well be a load issue.

**Comment by wertercatt** [comment]
> > This also happens to me when the server shuts down.
> 
> 
> 
> That's interesting, you mean on any regular server restarts? Have you by any chance changed the speed of the trains in the config? Do you have any server-side optimisation mods that could mess with loading? We do have some new code in version 1.2.4 to try to prevent this, although if you already had to a loader that shouldn't have happened before either

I haven't touched the Little Logistics config, I simply added it to Bliss. The server does have some intense lag when loading chunks, and yeah, whenever I run /stop and then bring the Server back up, the train is disconnected and my chains have been eaten. I'll 7z up the server files and attach them here shortly.

**Comment by MuradAkh** [comment]
Hmm actually minecolonies does some chunkloading stuff on its own, I wonder if there's some sort of interaction? Could be possible it unloads all chunks in the area even those claimed by the train. Maybe try removing the chunkloader car since you already have minecolonies to load it

**Comment by wertercatt** [comment]
https://wertercatt.com/Modified-Bliss-Server.7z

Train is setup in a public mine at a village found at 587, 65, 532

There should be a ferry from Spawn that picks up at -6, 63, 79

But with the bug, it is likely that the ferry has disconnected itself as well.

**Comment by MuradAkh** [comment]
> Ok, I'll see what we can do re: videos. We have 22 players, so it is likely the size. We have it embedded in Minecolonies and each of those colonies can have 50 to 250 citizens (entities). It might very well be a load issue.

I wonder if it could be some compat issue between little logistics chunkloading and minecolonies, perhaps minecolonies force unloads some of our chunks. I'm gonna look into their code and see if I suspect anything. 

Maybe you could try removing the chunkloader cars since it's already loaded with minecolonies?

**Comment by EDToaster** [comment]
chunkloader cars are deprecated now in favour of the tug registration system -- please open another issue if the same problem occurs.
